"""add_resume_text_and_ai_score

Revision ID: a57565ad8876
Revises: 0001
Create Date: 2026-02-18 00:59:49.514760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57565ad8876'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('ai_match_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'ai_match_score')
    op.drop_column('candidates', 'resume_text')
    # ### end Alembic commands ###
